version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123567
      - POSTGRES_DB=justtalk
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:123567@postgres:5432/justtalk?sslmode=disable
    depends_on:
      - postgres
    entrypoint: ["/usr/app/wait-for.sh", "postgres:5432", "--", "/usr/app/start.sh"]
    command: ["/usr/app/main"]

