version: "3.9"
services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123567
      - POSTGRES_DB=justtalk
  redis:
    image: redis
    volumes:
      - redis_data:/data
    ports:
      - "6380:6379"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9101:9101"
    environment:
      - DB_SOURCE=postgresql://root:123567@postgres:5432/justtalk?sslmode=disable
    depends_on:
      - postgres
      - redis
      - rabbitmq
    entrypoint: ["/usr/app/wait-for.sh", "postgres:5432", "--", "/usr/app/start.sh"]
    command: ["/usr/app/main"]
  rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:

