// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type Friendship struct {
	ID       int64     `json:"id"`
	FromID   int64     `json:"from_id"`
	ToID     int64     `json:"to_id"`
	Status   int16     `json:"status"`
	CreateAt time.Time `json:"create_at"`
	UpdateAt time.Time `json:"update_at"`
}

type Message struct {
	ID         int64     `json:"id"`
	SenderID   int64     `json:"sender_id"`
	ReceiverID int64     `json:"receiver_id"`
	Content    string    `json:"content"`
	SendAt     time.Time `json:"send_at"`
}

type User struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Password    string    `json:"password"`
	Nickname    string    `json:"nickname"`
	AvatarUrl   string    `json:"avatar_url"`
	FriendCount int32     `json:"friend_count"`
	Friends     []int64   `json:"friends"`
	CreateAt    time.Time `json:"create_at"`
	UpdateAt    time.Time `json:"update_at"`
}
