// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type Friendship struct {
	ID       int64     `json:"id"`
	FromId   int64     `json:"fromId"`
	ToId     int64     `json:"toId"`
	Status   int16     `json:"status"`
	CreateAt time.Time `json:"createAt"`
	UpdateAt time.Time `json:"updateAt"`
}

type Message struct {
	ID         int64     `json:"id"`
	SenderId   int64     `json:"senderId"`
	ReceiverId int64     `json:"receiverId"`
	Content    string    `json:"content"`
	SendAt     time.Time `json:"sendAt"`
}

type User struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Password    string    `json:"password"`
	Nickname    string    `json:"nickname"`
	AvatarURL   string    `json:"avatarURL"`
	FriendCount int32     `json:"friendCount"`
	Friends     []int64   `json:"friends"`
	CreateAt    time.Time `json:"createAt"`
	UpdateAt    time.Time `json:"updateAt"`
}
