// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateFriendShip(ctx context.Context, arg CreateFriendShipParams) (Friendship, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteFriendShip(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetFriendShip(ctx context.Context, id int64) (Friendship, error)
	GetUser(ctx context.Context, id int64) (User, error)
	ListFriendShip(ctx context.Context, arg ListFriendShipParams) ([]Friendship, error)
	ListUser(ctx context.Context, arg ListUserParams) ([]User, error)
	UpdateFriendShip(ctx context.Context, arg UpdateFriendShipParams) error
	UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error
}

var _ Querier = (*Queries)(nil)
